name: Scrape data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"  # Runs daily at 4am EST

jobs:
  scrape-data:
    runs-on: ubuntu-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install package dependencies
        run: pip install -r requirements.txt

      - name: Scrape data
        env:
          WEBSHARE_TOKEN: ${{ secrets.WEBSHARE_TOKEN }}
        run: python src/lineup_data.py

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
